### ISSUE TITLE
设置界面的字体名称较长，显示不全

### ISSUE THREAD

**Issue by xuelingkang** [kanyways/rdm#10]
![iShot2021-05-30 23 25 02](https://user-images.githubusercontent.com/42362195/120110028-9395e580-c19e-11eb-8e54-09b128fa6e74.png)
拉伸窗口，鼠标悬浮等操作都不能显示全名，请问有什么办法吗

**Comment by kanyways** [comment]
兄台，这个问题您需要找开发者。

**Comment by kanyways** [comment]
这个字体在选择的时候可以显示全了，不知道是不是你想要的，在2021.5.9999 dmg这个版本。等我发布

**Comment by xuelingkang** [comment]
谢谢，我后来也发现了，上一个版本已经支持了。
