### ISSUE TITLE
External: Can't load list of available formatters from extension server: Protocol "" is unknown,  Connection: Disconnect on error: Connection timeout

### ISSUE THREAD

**Issue by jianhu2** [kanyways/rdm#16]
版本：resp-2022.4.999
系统: windows: 10
现象：
External: Can't load list of available formatters from extension server: Protocol "" is unknown, 
Connection: Disconnect on error: Connection timeout

我想要使用SSH方式连接redis，发现以上错误
有人遇到过这样的问题吗，我该怎么解决

**Comment by kanyways** [comment]
这个没有遇见过，不知道你怎么用的，个人用的很舒适。

**Comment by Ray2310** [comment]
这是因为你的ip发生了变化，去虚拟机或者linux系统下 ，用IP addr 查看新的ip地址，然后重新连接REST
