### ISSUE TITLE
编译的运行程序在Win10 上不显示应用文字

### ISSUE THREAD

**Issue by FUCKU** [kanyways/rdm#5]
编译的运行程序在Win10 上不显示输入框内容，从登陆信息设置到程序设置，几乎所有的输入框都看不见内容，

Windows 10 专业工作站版 20H2 ，版本号 19042.746

**Comment by kanyways** [comment]
![image](https://user-images.githubusercontent.com/9895669/106877539-d295bc00-6713-11eb-8319-c5068f53ae76.png)

![image](https://user-images.githubusercontent.com/9895669/106877594-e3463200-6713-11eb-97a0-68eee3c33489.png)

Windows 10 企业版
20H2
19042.508
